version: "3.7"
services:
  postgres:
    container_name: helpdesk-db
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./.var/postgresql:/var/lib/postgresql/data
    ports:
      - "5435:5432"
  redis:
    container_name: helpdesk-redis
    image: redis:6-alpine
    volumes:
      - ./.var/redis:/data
    ports:
      - "6379:6379"
  app:
    container_name: helpdesk-app
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
      - celery
  celery:
    container_name: helpdesk-celery
    build: .
    command: celery -A helpdesk worker
    volumes:
      - .:/app
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis